// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bugs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bugCreate = `-- name: BugCreate :one
INSERT INTO bugs (game_url, os, browser, version, description)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type BugCreateParams struct {
	GameUrl     string      `json:"game_url"`
	Os          string      `json:"os"`
	Browser     string      `json:"browser"`
	Version     pgtype.Text `json:"version"`
	Description string      `json:"description"`
}

func (q *Queries) BugCreate(ctx context.Context, arg BugCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, bugCreate,
		arg.GameUrl,
		arg.Os,
		arg.Browser,
		arg.Version,
		arg.Description,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const bugDelete = `-- name: BugDelete :exec
DELETE FROM bugs
WHERE id = $1
`

func (q *Queries) BugDelete(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, bugDelete, id)
	return err
}

const bugGet = `-- name: BugGet :one
SELECT id, game_url, os, browser, version, description, status, issue_url, notes, created FROM bugs
WHERE id = $1
`

func (q *Queries) BugGet(ctx context.Context, id int32) (Bugs, error) {
	row := q.db.QueryRow(ctx, bugGet, id)
	var i Bugs
	err := row.Scan(
		&i.ID,
		&i.GameUrl,
		&i.Os,
		&i.Browser,
		&i.Version,
		&i.Description,
		&i.Status,
		&i.IssueUrl,
		&i.Notes,
		&i.Created,
	)
	return i, err
}

const bugSetStatus = `-- name: BugSetStatus :exec
UPDATE bugs
SET status = $2,
    issue_url = $3,
    notes = $4
WHERE id = $1
`

type BugSetStatusParams struct {
	ID       int32       `json:"id"`
	Status   string      `json:"status"`
	IssueUrl pgtype.Text `json:"issue_url"`
	Notes    pgtype.Text `json:"notes"`
}

func (q *Queries) BugSetStatus(ctx context.Context, arg BugSetStatusParams) error {
	_, err := q.db.Exec(ctx, bugSetStatus,
		arg.ID,
		arg.Status,
		arg.IssueUrl,
		arg.Notes,
	)
	return err
}

const bugsNew = `-- name: BugsNew :many
SELECT id, game_url, os, browser, version, description, status, issue_url, notes, created FROM bugs
WHERE status = 'new'
ORDER BY created
`

func (q *Queries) BugsNew(ctx context.Context) ([]Bugs, error) {
	rows, err := q.db.Query(ctx, bugsNew)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bugs
	for rows.Next() {
		var i Bugs
		if err := rows.Scan(
			&i.ID,
			&i.GameUrl,
			&i.Os,
			&i.Browser,
			&i.Version,
			&i.Description,
			&i.Status,
			&i.IssueUrl,
			&i.Notes,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
