// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: cache.sql

package sqlc

import (
	"context"
)

const cacheClean = `-- name: CacheClean :exec
DELETE FROM game_cache
WHERE expires <= CURRENT_TIMESTAMP
`

func (q *Queries) CacheClean(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cacheClean)
	return err
}

const cacheGet = `-- name: CacheGet :one
SELECT value FROM game_cache
WHERE game_id = $1 AND expires > CURRENT_TIMESTAMP
`

func (q *Queries) CacheGet(ctx context.Context, gameID string) ([]byte, error) {
	row := q.db.QueryRow(ctx, cacheGet, gameID)
	var value []byte
	err := row.Scan(&value)
	return value, err
}

const cacheSet = `-- name: CacheSet :exec
INSERT INTO game_cache (game_id, value, expires)
VALUES ($1, $2, CURRENT_TIMESTAMP + INTERVAL '1 second') -- TODO: make var?
ON CONFLICT (game_id) DO UPDATE SET 
    value = EXCLUDED.value, 
    expires = EXCLUDED.expires
`

type CacheSetParams struct {
	GameID string `json:"game_id"`
	Value  []byte `json:"value"`
}

func (q *Queries) CacheSet(ctx context.Context, arg CacheSetParams) error {
	_, err := q.db.Exec(ctx, cacheSet, arg.GameID, arg.Value)
	return err
}
