// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cards.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const card = `-- name: Card :one
SELECT id, type, front, back, creator, created, generic FROM cards WHERE id = $1
`

func (q *Queries) Card(ctx context.Context, id int32) (Cards, error) {
	row := q.db.QueryRow(ctx, card, id)
	var i Cards
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Front,
		&i.Back,
		&i.Creator,
		&i.Created,
		&i.Generic,
	)
	return i, err
}

const cardCreate = `-- name: CardCreate :exec
INSERT INTO cards (type, front, back, creator)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CardCreateParams struct {
	Type    string      `json:"type"`
	Front   string      `json:"front"`
	Back    pgtype.Text `json:"back"`
	Creator pgtype.Int4 `json:"creator"`
}

func (q *Queries) CardCreate(ctx context.Context, arg CardCreateParams) error {
	_, err := q.db.Exec(ctx, cardCreate,
		arg.Type,
		arg.Front,
		arg.Back,
		arg.Creator,
	)
	return err
}

const cardDelete = `-- name: CardDelete :exec
DELETE FROM cards WHERE id = $1
`

func (q *Queries) CardDelete(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, cardDelete, id)
	return err
}
