// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const eventCreate = `-- name: EventCreate :one
INSERT INTO event_log (
    game_id, event_type, actor_id, target_id,
    spin_id, infraction_id, game_card_id, point_change_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type EventCreateParams struct {
	GameID        string      `json:"game_id"`
	EventType     string      `json:"event_type"`
	ActorID       pgtype.Int4 `json:"actor_id"`
	TargetID      pgtype.Int4 `json:"target_id"`
	SpinID        pgtype.Int4 `json:"spin_id"`
	InfractionID  pgtype.Int4 `json:"infraction_id"`
	GameCardID    pgtype.Int4 `json:"game_card_id"`
	PointChangeID pgtype.Int4 `json:"point_change_id"`
}

// Appends one event to the log. Detail FKs (spin_id, infraction_id,
// game_card_id, point_change_id) are set per event_type; the rest are NULL.
func (q *Queries) EventCreate(ctx context.Context, arg EventCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, eventCreate,
		arg.GameID,
		arg.EventType,
		arg.ActorID,
		arg.TargetID,
		arg.SpinID,
		arg.InfractionID,
		arg.GameCardID,
		arg.PointChangeID,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const eventListSince = `-- name: EventListSince :many
SELECT id, game_id, event_type, actor_id, target_id,
    spin_id, infraction_id, game_card_id, point_change_id, ts
FROM event_log
WHERE game_id = $1
    AND id > $2
ORDER BY id
`

type EventListSinceParams struct {
	GameID string `json:"game_id"`
	ID     int32  `json:"id"`
}

// Events for a game newer than a given id, oldest first. Clients track the
// highest id they have seen and poll for the rest.
func (q *Queries) EventListSince(ctx context.Context, arg EventListSinceParams) ([]EventLog, error) {
	rows, err := q.db.Query(ctx, eventListSince, arg.GameID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventLog
	for rows.Next() {
		var i EventLog
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.EventType,
			&i.ActorID,
			&i.TargetID,
			&i.SpinID,
			&i.InfractionID,
			&i.GameCardID,
			&i.PointChangeID,
			&i.Ts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
