// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const eventCreate = `-- name: EventCreate :one
INSERT INTO event_log (
    game_id, event_type, actor_id, target_id,
    spin_id, infraction_id, game_card_id, point_change_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type EventCreateParams struct {
	GameID        string      `json:"game_id"`
	EventType     string      `json:"event_type"`
	ActorID       pgtype.Int4 `json:"actor_id"`
	TargetID      pgtype.Int4 `json:"target_id"`
	SpinID        pgtype.Int4 `json:"spin_id"`
	InfractionID  pgtype.Int4 `json:"infraction_id"`
	GameCardID    pgtype.Int4 `json:"game_card_id"`
	PointChangeID pgtype.Int4 `json:"point_change_id"`
}

// Appends one event to the log. Detail FKs (spin_id, infraction_id,
// game_card_id, point_change_id) are set per event_type; the rest are NULL.
func (q *Queries) EventCreate(ctx context.Context, arg EventCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, eventCreate,
		arg.GameID,
		arg.EventType,
		arg.ActorID,
		arg.TargetID,
		arg.SpinID,
		arg.InfractionID,
		arg.GameCardID,
		arg.PointChangeID,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const eventListSince = `-- name: EventListSince :many
SELECT
    e.id,
    e.event_type,
    actor.name AS actor_name,
    target.name AS target_name,
    pc.delta AS points_delta,
    inf.affirmed AS infraction_affirmed,
    -- the card this event is about, from whichever detail table holds it:
    -- game_cards for flip/shred/clone/transfer, spins for spin, the accused
    -- rule for accuse/decide. COALESCE to '' so events with no card scan as an
    -- empty string instead of NULL; the template treats '' as "no card".
    COALESCE((SELECT c.front FROM cards c
        WHERE c.id = COALESCE(gc.card_id, sp.card_id, inf_gc.card_id)), '')::text AS card_front,
    COALESCE((SELECT c.back FROM cards c
        WHERE c.id = COALESCE(gc.card_id, sp.card_id, inf_gc.card_id)), '')::text AS card_back,
    COALESCE((SELECT c.type FROM cards c
        WHERE c.id = COALESCE(gc.card_id, sp.card_id, inf_gc.card_id)), '')::text AS card_type,
    COALESCE(gc.flipped, inf_gc.flipped, FALSE) AS card_flipped
FROM event_log e
LEFT JOIN players actor ON actor.id = e.actor_id
LEFT JOIN players target ON target.id = e.target_id
LEFT JOIN point_changes pc ON pc.id = e.point_change_id
LEFT JOIN infractions inf ON inf.id = e.infraction_id
LEFT JOIN game_cards gc ON gc.id = e.game_card_id
LEFT JOIN spins sp ON sp.id = e.spin_id
LEFT JOIN game_cards inf_gc ON inf_gc.id = inf.game_card_id
WHERE e.game_id = $1
    AND e.id > $2
ORDER BY e.id
`

type EventListSinceParams struct {
	GameID string `json:"game_id"`
	ID     int32  `json:"id"`
}

type EventListSinceRow struct {
	ID                 int32       `json:"id"`
	EventType          string      `json:"event_type"`
	ActorName          pgtype.Text `json:"actor_name"`
	TargetName         pgtype.Text `json:"target_name"`
	PointsDelta        pgtype.Int4 `json:"points_delta"`
	InfractionAffirmed pgtype.Bool `json:"infraction_affirmed"`
	CardFront          string      `json:"card_front"`
	CardBack           string      `json:"card_back"`
	CardType           string      `json:"card_type"`
	CardFlipped        bool        `json:"card_flipped"`
}

// Events for a game newer than a given id, oldest first, with the names and
// details the feed text and sounds need. Clients track the highest id seen.
func (q *Queries) EventListSince(ctx context.Context, arg EventListSinceParams) ([]EventListSinceRow, error) {
	rows, err := q.db.Query(ctx, eventListSince, arg.GameID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventListSinceRow
	for rows.Next() {
		var i EventListSinceRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.ActorName,
			&i.TargetName,
			&i.PointsDelta,
			&i.InfractionAffirmed,
			&i.CardFront,
			&i.CardBack,
			&i.CardType,
			&i.CardFlipped,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
