// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: game.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const gameCreate = `-- name: GameCreate :exec
INSERT INTO games (name, id, owner_id)
VALUES ($1, $2, $3)
RETURNING id
`

type GameCreateParams struct {
	Name    string      `json:"name"`
	ID      string      `json:"id"`
	OwnerID pgtype.Int4 `json:"owner_id"`
}

func (q *Queries) GameCreate(ctx context.Context, arg GameCreateParams) error {
	_, err := q.db.Exec(ctx, gameCreate, arg.Name, arg.ID, arg.OwnerID)
	return err
}

const gameDelete = `-- name: GameDelete :exec
DELETE FROM games WHERE id = $1
`

func (q *Queries) GameDelete(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, gameDelete, id)
	return err
}

const gameState = `-- name: GameState :one
SELECT
    id,
    name,
    owner_id,
    state_id,
    initiative_current,
    (
        SELECT name
        FROM game_states
        WHERE game_states.id = state_id
    ) AS state_name,
    (
        SELECT description
        FROM game_states
        WHERE game_states.id = state_id
    ) AS state_description,
    (
        SELECT COUNT(player_id)
        FROM game_players
        WHERE game_players.game_id = games.id
    ) AS player_count
FROM games WHERE games.id = $1
`

type GameStateRow struct {
	ID                string      `json:"id"`
	Name              string      `json:"name"`
	OwnerID           pgtype.Int4 `json:"owner_id"`
	StateID           int32       `json:"state_id"`
	InitiativeCurrent pgtype.Int4 `json:"initiative_current"`
	StateName         string      `json:"state_name"`
	StateDescription  pgtype.Text `json:"state_description"`
	PlayerCount       int64       `json:"player_count"`
}

func (q *Queries) GameState(ctx context.Context, id string) (GameStateRow, error) {
	row := q.db.QueryRow(ctx, gameState, id)
	var i GameStateRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.StateID,
		&i.InitiativeCurrent,
		&i.StateName,
		&i.StateDescription,
		&i.PlayerCount,
	)
	return i, err
}

const gameUpdate = `-- name: GameUpdate :exec
UPDATE games
SET state_id = $1, initiative_current = $2
WHERE id = $3
`

type GameUpdateParams struct {
	StateID           int32       `json:"state_id"`
	InitiativeCurrent pgtype.Int4 `json:"initiative_current"`
	ID                string      `json:"id"`
}

func (q *Queries) GameUpdate(ctx context.Context, arg GameUpdateParams) error {
	_, err := q.db.Exec(ctx, gameUpdate, arg.StateID, arg.InitiativeCurrent, arg.ID)
	return err
}

const games = `-- name: Games :many
SELECT id, name, created, owner_id, state_id, wheel_slots, card_count, initiative_timer, initiative_current FROM games WHERE id = (
	SELECT game_id 
	FROM game_players
	WHERE player_id = $1
)
`

func (q *Queries) Games(ctx context.Context, playerID int32) ([]Games, error) {
	rows, err := q.db.Query(ctx, games, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Games
	for rows.Next() {
		var i Games
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Created,
			&i.OwnerID,
			&i.StateID,
			&i.WheelSlots,
			&i.CardCount,
			&i.InitiativeTimer,
			&i.InitiativeCurrent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
