// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: game_cards.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const gameCardClone = `-- name: GameCardClone :exec
INSERT INTO game_cards (game_id, card_id, player_id, from_clone)
SELECT game_id, card_id, $2, TRUE
FROM game_cards
WHERE game_cards.id = $1
    AND player_id IS NOT NULL
    AND shredded = FALSE
`

type GameCardCloneParams struct {
	ID       int32       `json:"id"`
	PlayerID pgtype.Int4 `json:"player_id"`
}

func (q *Queries) GameCardClone(ctx context.Context, arg GameCardCloneParams) error {
	_, err := q.db.Exec(ctx, gameCardClone, arg.ID, arg.PlayerID)
	return err
}

const gameCardFlip = `-- name: GameCardFlip :exec
UPDATE game_cards
SET flipped = NOT flipped
WHERE id = $1
`

func (q *Queries) GameCardFlip(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, gameCardFlip, id)
	return err
}

const gameCardMove = `-- name: GameCardMove :exec

UPDATE game_cards
SET player_id = $2
WHERE id = $1
`

type GameCardMoveParams struct {
	ID       int32       `json:"id"`
	PlayerID pgtype.Int4 `json:"player_id"`
}

// GameCardCreate :exec
// TODO: after MVP, implement card creation phase
func (q *Queries) GameCardMove(ctx context.Context, arg GameCardMoveParams) error {
	_, err := q.db.Exec(ctx, gameCardMove, arg.ID, arg.PlayerID)
	return err
}

const gameCardShred = `-- name: GameCardShred :exec
UPDATE game_cards
SET shredded = TRUE
WHERE id = $1
`

func (q *Queries) GameCardShred(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, gameCardShred, id)
	return err
}

const gameCardsInitGeneric = `-- name: GameCardsInitGeneric :exec
INSERT INTO game_cards (
    game_id, 
    card_id, 
    slot, 
    stack, 
    player_id
) SELECT
    $1::text,
    id, 
    ((ROW_NUMBER() OVER ()) % (SELECT wheel_slots FROM games WHERE games.id = $1)) + 1,
    NULL, -- unshuffled
    NULL -- unrevealed
FROM cards 
WHERE generic IS TRUE LIMIT (SELECT card_count FROM games WHERE games.id = $1)
`

func (q *Queries) GameCardsInitGeneric(ctx context.Context, dollar_1 string) error {
	_, err := q.db.Exec(ctx, gameCardsInitGeneric, dollar_1)
	return err
}

const gameCardsPlayerView = `-- name: GameCardsPlayerView :many
SELECT
    id,
    player_id,
    from_clone,
    flipped,
    shredded,
    updated,
    slot,
    stack,
    (
        SELECT
            CASE
                WHEN flipped THEN back
                ELSE front
            END
        FROM cards 
        WHERE cards.id = game_cards.card_id
    ) AS content,
    (
        SELECT type FROM cards 
        WHERE cards.id = game_cards.card_id
    ) AS type,
    (
        SELECT generic FROM cards
        WHERE cards.id = game_cards.card_id
    ) AS generic,
    (
        SELECT modifier_effect FROM cards
        WHERE cards.id = game_cards.card_id
    ) AS modifier_effect
FROM game_cards
WHERE game_id = $1
    AND shredded IS FALSE
    AND player_id IS NOT NULL
`

type GameCardsPlayerViewRow struct {
	ID             int32            `json:"id"`
	PlayerID       pgtype.Int4      `json:"player_id"`
	FromClone      pgtype.Bool      `json:"from_clone"`
	Flipped        pgtype.Bool      `json:"flipped"`
	Shredded       pgtype.Bool      `json:"shredded"`
	Updated        pgtype.Timestamp `json:"updated"`
	Slot           pgtype.Int4      `json:"slot"`
	Stack          pgtype.Int4      `json:"stack"`
	Content        interface{}      `json:"content"`
	Type           string           `json:"type"`
	Generic        pgtype.Bool      `json:"generic"`
	ModifierEffect pgtype.Text      `json:"modifier_effect"`
}

func (q *Queries) GameCardsPlayerView(ctx context.Context, gameID string) ([]GameCardsPlayerViewRow, error) {
	rows, err := q.db.Query(ctx, gameCardsPlayerView, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameCardsPlayerViewRow
	for rows.Next() {
		var i GameCardsPlayerViewRow
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.FromClone,
			&i.Flipped,
			&i.Shredded,
			&i.Updated,
			&i.Slot,
			&i.Stack,
			&i.Content,
			&i.Type,
			&i.Generic,
			&i.ModifierEffect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const gameCardsShuffle = `-- name: GameCardsShuffle :exec
WITH ordered AS (
 SELECT
        card_id,
        slot,
        ROW_NUMBER() OVER (PARTITION BY slot ORDER BY RANDOM()) AS stack 
    FROM game_cards
    WHERE game_id = $1
)
UPDATE game_cards
SET stack = ordered.stack
FROM ordered
WHERE game_cards.game_id = $1
    AND game_cards.card_id = ordered.card_id
    AND game_cards.slot = ordered.slot
`

// shuffles stacks within a slot, leaving slot assignments unchanged
func (q *Queries) GameCardsShuffle(ctx context.Context, gameID string) error {
	_, err := q.db.Exec(ctx, gameCardsShuffle, gameID)
	return err
}

const gameCardsWheelSpin = `-- name: GameCardsWheelSpin :one
WITH spin AS (
    SELECT floor(random() * wheel_slots)::int + 1 AS random_slot
    FROM games
    WHERE games.id = $1
),
resultant_card AS (
    SELECT (
        SELECT game_cards.id
        FROM game_cards
        WHERE game_id = $1 
            AND slot = (SELECT random_slot FROM spin)
        ORDER BY stack DESC
        LIMIT 1
    ) AS id
),
spin_log AS (
    INSERT INTO spin_log (game_id, player_id, slot, card_id)
    VALUES (
        $1,
        $2,
        (SELECT random_slot FROM spin),
        (SELECT card_id FROM game_cards WHERE id = (
                SELECT id FROM resultant_card)
        )
    )
)
UPDATE game_cards
SET player_id = $2, slot = NULL, stack = NULL, updated = CURRENT_TIMESTAMP
WHERE game_cards.id = (SELECT id FROM resultant_card)
RETURNING id
`

type GameCardsWheelSpinParams struct {
	ID       string      `json:"id"`
	PlayerID pgtype.Int4 `json:"player_id"`
}

// sql.ErrNoRows = end of game
func (q *Queries) GameCardsWheelSpin(ctx context.Context, arg GameCardsWheelSpinParams) (int32, error) {
	row := q.db.QueryRow(ctx, gameCardsWheelSpin, arg.ID, arg.PlayerID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const gameCardsWheelView = `-- name: GameCardsWheelView :many
SELECT
    slot,
    (
        SELECT COUNT(id) 
        FROM game_cards 
        WHERE game_cards.game_id = $1 AND slot = game_cards.slot AND shredded IS FALSE
    ) AS stack_size,
    (
        SELECT type
        FROM cards 
        WHERE cards.id = (
            SELECT card_id 
            FROM game_cards 
            WHERE game_cards.game_id = $1 
                AND game_cards.slot = game_cards.slot 
                AND game_cards.shredded IS FALSE
            ORDER BY stack DESC LIMIT 1
        )
    ) AS top_card_type
FROM game_cards
WHERE game_id = $1 AND player_id IS NULL
ORDER BY slot ASC
`

type GameCardsWheelViewRow struct {
	Slot        pgtype.Int4 `json:"slot"`
	StackSize   int64       `json:"stack_size"`
	TopCardType string      `json:"top_card_type"`
}

// Public view of the unrevealed wheel.
func (q *Queries) GameCardsWheelView(ctx context.Context, gameID string) ([]GameCardsWheelViewRow, error) {
	rows, err := q.db.Query(ctx, gameCardsWheelView, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameCardsWheelViewRow
	for rows.Next() {
		var i GameCardsWheelViewRow
		if err := rows.Scan(&i.Slot, &i.StackSize, &i.TopCardType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
