// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: infractions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const infractionCreate = `-- name: InfractionCreate :one
INSERT INTO infractions (game_id, game_card_id, accused, accuser)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type InfractionCreateParams struct {
	GameID     string `json:"game_id"`
	GameCardID int32  `json:"game_card_id"`
	Accused    int32  `json:"accused"`
	Accuser    int32  `json:"accuser"`
}

func (q *Queries) InfractionCreate(ctx context.Context, arg InfractionCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, infractionCreate,
		arg.GameID,
		arg.GameCardID,
		arg.Accused,
		arg.Accuser,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const infractionDecide = `-- name: InfractionDecide :one
UPDATE infractions
SET active = FALSE,
    affirmed = $2
WHERE id = $1
    AND active = TRUE
RETURNING id
`

type InfractionDecideParams struct {
	ID       int32       `json:"id"`
	Affirmed pgtype.Bool `json:"affirmed"`
}

func (q *Queries) InfractionDecide(ctx context.Context, arg InfractionDecideParams) (int32, error) {
	row := q.db.QueryRow(ctx, infractionDecide, arg.ID, arg.Affirmed)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const infractionGet = `-- name: InfractionGet :one
SELECT id, game_id, game_card_id, accused, accuser, created, active, affirmed, transfer_pending FROM infractions
WHERE id = $1
`

func (q *Queries) InfractionGet(ctx context.Context, id int32) (Infractions, error) {
	row := q.db.QueryRow(ctx, infractionGet, id)
	var i Infractions
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.GameCardID,
		&i.Accused,
		&i.Accuser,
		&i.Created,
		&i.Active,
		&i.Affirmed,
		&i.TransferPending,
	)
	return i, err
}

const infractionTransferArm = `-- name: InfractionTransferArm :exec
UPDATE infractions
SET transfer_pending = TRUE
WHERE id = $1
`

func (q *Queries) InfractionTransferArm(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, infractionTransferArm, id)
	return err
}

const infractionTransferPending = `-- name: InfractionTransferPending :one
SELECT id, game_card_id, accused, accuser
FROM infractions
WHERE game_id = $1
    AND affirmed = TRUE
    AND transfer_pending = TRUE
ORDER BY created DESC
LIMIT 1
`

type InfractionTransferPendingRow struct {
	ID         int32 `json:"id"`
	GameCardID int32 `json:"game_card_id"`
	Accused    int32 `json:"accused"`
	Accuser    int32 `json:"accuser"`
}

func (q *Queries) InfractionTransferPending(ctx context.Context, gameID string) (InfractionTransferPendingRow, error) {
	row := q.db.QueryRow(ctx, infractionTransferPending, gameID)
	var i InfractionTransferPendingRow
	err := row.Scan(
		&i.ID,
		&i.GameCardID,
		&i.Accused,
		&i.Accuser,
	)
	return i, err
}

const infractionTransferResolve = `-- name: InfractionTransferResolve :exec
UPDATE infractions
SET transfer_pending = FALSE
WHERE id = $1
`

func (q *Queries) InfractionTransferResolve(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, infractionTransferResolve, id)
	return err
}

const infractionsActiveCount = `-- name: InfractionsActiveCount :one
SELECT COUNT(*) FROM infractions
WHERE game_id = $1
    AND active = TRUE
`

func (q *Queries) InfractionsActiveCount(ctx context.Context, gameID string) (int64, error) {
	row := q.db.QueryRow(ctx, infractionsActiveCount, gameID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const infractionsByGame = `-- name: InfractionsByGame :many
SELECT id, game_id, game_card_id, accused, accuser, created, active, affirmed, transfer_pending
FROM infractions
WHERE game_id = $1
ORDER BY created DESC
`

func (q *Queries) InfractionsByGame(ctx context.Context, gameID string) ([]Infractions, error) {
	rows, err := q.db.Query(ctx, infractionsByGame, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Infractions
	for rows.Next() {
		var i Infractions
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.GameCardID,
			&i.Accused,
			&i.Accuser,
			&i.Created,
			&i.Active,
			&i.Affirmed,
			&i.TransferPending,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
