// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: infractions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const infractionCreate = `-- name: InfractionCreate :one
INSERT INTO infractions (game_id, game_card_id, accused, accuser)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type InfractionCreateParams struct {
	GameID     string `json:"game_id"`
	GameCardID int32  `json:"game_card_id"`
	Accused    int32  `json:"accused"`
	Accuser    int32  `json:"accuser"`
}

func (q *Queries) InfractionCreate(ctx context.Context, arg InfractionCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, infractionCreate,
		arg.GameID,
		arg.GameCardID,
		arg.Accused,
		arg.Accuser,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const infractionDecide = `-- name: InfractionDecide :exec
UPDATE infractions
SET active = FALSE,
    affirmed = $2,
    points = $3
WHERE id = $1
    AND active = TRUE
`

type InfractionDecideParams struct {
	ID       int32       `json:"id"`
	Affirmed pgtype.Bool `json:"affirmed"`
	Points   pgtype.Int4 `json:"points"`
}

func (q *Queries) InfractionDecide(ctx context.Context, arg InfractionDecideParams) error {
	_, err := q.db.Exec(ctx, infractionDecide, arg.ID, arg.Affirmed, arg.Points)
	return err
}

const infractionGet = `-- name: InfractionGet :one
SELECT id, game_id, game_card_id, accused, accuser, created, active, affirmed, points FROM infractions
WHERE id = $1
`

func (q *Queries) InfractionGet(ctx context.Context, id int32) (Infractions, error) {
	row := q.db.QueryRow(ctx, infractionGet, id)
	var i Infractions
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.GameCardID,
		&i.Accused,
		&i.Accuser,
		&i.Created,
		&i.Active,
		&i.Affirmed,
		&i.Points,
	)
	return i, err
}

const infractionUpdatePoints = `-- name: InfractionUpdatePoints :exec
UPDATE game_players
SET points = points - $1
WHERE game_id = $2
    AND player_id = $3
`

type InfractionUpdatePointsParams struct {
	Points   pgtype.Int4 `json:"points"`
	GameID   string      `json:"game_id"`
	PlayerID int32       `json:"player_id"`
}

func (q *Queries) InfractionUpdatePoints(ctx context.Context, arg InfractionUpdatePointsParams) error {
	_, err := q.db.Exec(ctx, infractionUpdatePoints, arg.Points, arg.GameID, arg.PlayerID)
	return err
}
