// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: initiative.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const initiativeAdvance = `-- name: InitiativeAdvance :exec
WITH cur AS (
  SELECT initiative_current FROM games WHERE id = $1
)
UPDATE games
SET initiative_current = COALESCE(
  (
    SELECT MIN(game_players.initiative)
    FROM game_players, cur
    WHERE game_players.game_id = $1
      AND game_players.initiative > 0
      AND game_players.initiative > cur.initiative_current
  ),
  (
    SELECT MIN(game_players.initiative)
    FROM game_players
    WHERE game_players.game_id = $1
      AND game_players.initiative > 0
  )
)
WHERE games.id = $1
`

// Move initiative to the next non-host player, skipping empty slots left by
// players who exited, and wrapping back to the lowest when past the top.
func (q *Queries) InitiativeAdvance(ctx context.Context, gameID string) error {
	_, err := q.db.Exec(ctx, initiativeAdvance, gameID)
	return err
}

const initiativeCurrentPlayer = `-- name: InitiativeCurrentPlayer :one
SELECT game_players.player_id
FROM game_players
JOIN games ON games.id = game_players.game_id
WHERE game_players.game_id = $1
    AND game_players.initiative = games.initiative_current
`

// The player whose turn it is now (initiative matches the game's current).
func (q *Queries) InitiativeCurrentPlayer(ctx context.Context, gameID string) (int32, error) {
	row := q.db.QueryRow(ctx, initiativeCurrentPlayer, gameID)
	var player_id int32
	err := row.Scan(&player_id)
	return player_id, err
}

const initiativeSet = `-- name: InitiativeSet :exec
UPDATE game_players
SET initiative = $1
WHERE game_id = $2
    AND player_id = $3
`

type InitiativeSetParams struct {
	Initiative pgtype.Int4 `json:"initiative"`
	GameID     string      `json:"game_id"`
	PlayerID   int32       `json:"player_id"`
}

// TODO: unused?
func (q *Queries) InitiativeSet(ctx context.Context, arg InitiativeSetParams) error {
	_, err := q.db.Exec(ctx, initiativeSet, arg.Initiative, arg.GameID, arg.PlayerID)
	return err
}
