// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: initiative.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const initiativeAdvance = `-- name: InitiativeAdvance :exec
WITH initiative_max AS (
  SELECT MAX(game_players.initiative) AS highest
  FROM game_players
  WHERE game_players.game_id = $1
)
UPDATE games
SET initiative_current = (
  games.initiative_current % initiative_max.highest
) + 1
FROM initiative_max
WHERE games.id = $1
`

func (q *Queries) InitiativeAdvance(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, initiativeAdvance, id)
	return err
}

const initiativeSet = `-- name: InitiativeSet :exec
UPDATE game_players
SET initiative = $1
WHERE game_id = $2
    AND player_id = $3
`

type InitiativeSetParams struct {
	Initiative pgtype.Int4 `json:"initiative"`
	GameID     string      `json:"game_id"`
	PlayerID   int32       `json:"player_id"`
}

// TODO: unused?
func (q *Queries) InitiativeSet(ctx context.Context, arg InitiativeSetParams) error {
	_, err := q.db.Exec(ctx, initiativeSet, arg.Initiative, arg.GameID, arg.PlayerID)
	return err
}
