// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: log.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const spinLogPendingModifier = `-- name: SpinLogPendingModifier :one
SELECT
    spin_log.player_id,
    spin_log.card_id,
    cards.modifier_effect
FROM spin_log
JOIN cards ON cards.id = spin_log.card_id
WHERE spin_log.game_id = $1
ORDER BY spin_log.ts DESC
LIMIT 1
`

type SpinLogPendingModifierRow struct {
	PlayerID       pgtype.Int4 `json:"player_id"`
	CardID         pgtype.Int4 `json:"card_id"`
	ModifierEffect pgtype.Text `json:"modifier_effect"`
}

// Returns the most recent spin for a game, with modifier info.
// A non-NULL modifier_effect means the spin landed on a modifier.
func (q *Queries) SpinLogPendingModifier(ctx context.Context, gameID string) (SpinLogPendingModifierRow, error) {
	row := q.db.QueryRow(ctx, spinLogPendingModifier, gameID)
	var i SpinLogPendingModifierRow
	err := row.Scan(&i.PlayerID, &i.CardID, &i.ModifierEffect)
	return i, err
}
