// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CardTypes struct {
	Name string `json:"name"`
}

type Cards struct {
	ID      int32            `json:"id"`
	Type    string           `json:"type"`
	Front   string           `json:"front"`
	Back    pgtype.Text      `json:"back"`
	Creator pgtype.Int4      `json:"creator"`
	Created pgtype.Timestamp `json:"created"`
	Generic pgtype.Bool      `json:"generic"`
}

type GameCards struct {
	ID        int32       `json:"id"`
	GameID    string      `json:"game_id"`
	CardID    int32       `json:"card_id"`
	Slot      int32       `json:"slot"`
	Stack     int32       `json:"stack"`
	PlayerID  pgtype.Int4 `json:"player_id"`
	Revealed  pgtype.Bool `json:"revealed"`
	Flipped   pgtype.Bool `json:"flipped"`
	Shredded  pgtype.Bool `json:"shredded"`
	FromClone pgtype.Bool `json:"from_clone"`
}

type GamePlayers struct {
	GameID     string           `json:"game_id"`
	PlayerID   int32            `json:"player_id"`
	Points     pgtype.Int4      `json:"points"`
	SessionKey pgtype.Text      `json:"session_key"`
	Joined     pgtype.Timestamp `json:"joined"`
	Initiative pgtype.Int4      `json:"initiative"`
}

type GameStates struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Games struct {
	ID                string           `json:"id"`
	Name              string           `json:"name"`
	Created           pgtype.Timestamp `json:"created"`
	OwnerID           pgtype.Int4      `json:"owner_id"`
	StateID           int32            `json:"state_id"`
	InitiativeCurrent pgtype.Int4      `json:"initiative_current"`
}

type Infractions struct {
	ID        int32            `json:"id"`
	GameID    string           `json:"game_id"`
	Accused   int32            `json:"accused"`
	Accuser   int32            `json:"accuser"`
	Created   pgtype.Timestamp `json:"created"`
	Active    pgtype.Bool      `json:"active"`
	Convicted pgtype.Bool      `json:"convicted"`
}

type Players struct {
	ID      int32            `json:"id"`
	Name    string           `json:"name"`
	Created pgtype.Timestamp `json:"created"`
}
