// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
)

type CardTypes struct {
	Name string `json:"name"`
}

type Cards struct {
	ID      int64          `json:"id"`
	Type    string         `json:"type"`
	Front   string         `json:"front"`
	Back    sql.NullString `json:"back"`
	Creator sql.NullInt64  `json:"creator"`
	Created sql.NullTime   `json:"created"`
	Default sql.NullBool   `json:"default"`
}

type GameCards struct {
	ID        int64         `json:"id"`
	GameID    string        `json:"game_id"`
	CardID    int64         `json:"card_id"`
	Slot      int64         `json:"slot"`
	Stack     int64         `json:"stack"`
	PlayerID  sql.NullInt64 `json:"player_id"`
	Revealed  sql.NullBool  `json:"revealed"`
	Flipped   sql.NullBool  `json:"flipped"`
	Shredded  sql.NullBool  `json:"shredded"`
	FromClone sql.NullBool  `json:"from_clone"`
}

type GamePlayers struct {
	GameID     int64         `json:"game_id"`
	PlayerID   int64         `json:"player_id"`
	Points     sql.NullInt64 `json:"points"`
	Joined     sql.NullTime  `json:"joined"`
	Initiative sql.NullInt64 `json:"initiative"`
}

type GameStates struct {
	Name string `json:"name"`
}

type Games struct {
	Name              string        `json:"name"`
	ID                string        `json:"id"`
	Created           sql.NullTime  `json:"created"`
	OwnerID           int64         `json:"owner_id"`
	State             string        `json:"state"`
	InitiativeCurrent sql.NullInt64 `json:"initiative_current"`
}

type Infractions struct {
	ID        int64        `json:"id"`
	GameID    string       `json:"game_id"`
	Accused   int64        `json:"accused"`
	Accuser   int64        `json:"accuser"`
	Created   sql.NullTime `json:"created"`
	Active    sql.NullBool `json:"active"`
	Convicted sql.NullBool `json:"convicted"`
}

type Players struct {
	ID      int64        `json:"id"`
	Name    string       `json:"name"`
	Created sql.NullTime `json:"created"`
}
