// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: player.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const gamePlayerCreate = `-- name: GamePlayerCreate :exec
INSERT INTO game_players (game_id, player_id, session_key, initiative)
VALUES ($1, $2, $3, $4)
`

type GamePlayerCreateParams struct {
	GameID     string      `json:"game_id"`
	PlayerID   int32       `json:"player_id"`
	SessionKey pgtype.Text `json:"session_key"`
	Initiative pgtype.Int4 `json:"initiative"`
}

// session_key is expected to be valid for the duration of the game
func (q *Queries) GamePlayerCreate(ctx context.Context, arg GamePlayerCreateParams) error {
	_, err := q.db.Exec(ctx, gamePlayerCreate,
		arg.GameID,
		arg.PlayerID,
		arg.SessionKey,
		arg.Initiative,
	)
	return err
}

const gamePlayerDelete = `-- name: GamePlayerDelete :exec
DELETE FROM game_players 
WHERE game_id = $1 
	AND player_id = $2
`

type GamePlayerDeleteParams struct {
	GameID   string `json:"game_id"`
	PlayerID int32  `json:"player_id"`
}

func (q *Queries) GamePlayerDelete(ctx context.Context, arg GamePlayerDeleteParams) error {
	_, err := q.db.Exec(ctx, gamePlayerDelete, arg.GameID, arg.PlayerID)
	return err
}

const gamePlayerPoints = `-- name: GamePlayerPoints :many
SELECT 
    player_id,
    (SELECT name FROM players WHERE players.id=game_players.player_id) AS name, 
    points,
    session_key,
    initiative
FROM game_players 
WHERE game_id = $1
ORDER BY initiative ASC
`

type GamePlayerPointsRow struct {
	PlayerID   int32       `json:"player_id"`
	Name       string      `json:"name"`
	Points     pgtype.Int4 `json:"points"`
	SessionKey pgtype.Text `json:"session_key"`
	Initiative pgtype.Int4 `json:"initiative"`
}

// TODO: is id=player_id correct?
func (q *Queries) GamePlayerPoints(ctx context.Context, gameID string) ([]GamePlayerPointsRow, error) {
	rows, err := q.db.Query(ctx, gamePlayerPoints, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GamePlayerPointsRow
	for rows.Next() {
		var i GamePlayerPointsRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.Name,
			&i.Points,
			&i.SessionKey,
			&i.Initiative,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const gamePointsAdjust = `-- name: GamePointsAdjust :exec
UPDATE game_players
SET points = points + $1
WHERE game_id = $2
  AND player_id = $3
`

type GamePointsAdjustParams struct {
	Points   pgtype.Int4 `json:"points"`
	GameID   string      `json:"game_id"`
	PlayerID int32       `json:"player_id"`
}

func (q *Queries) GamePointsAdjust(ctx context.Context, arg GamePointsAdjustParams) error {
	_, err := q.db.Exec(ctx, gamePointsAdjust, arg.Points, arg.GameID, arg.PlayerID)
	return err
}

const player = `-- name: Player :one
SELECT id, name, created FROM players WHERE id = $1
`

func (q *Queries) Player(ctx context.Context, id int32) (Players, error) {
	row := q.db.QueryRow(ctx, player, id)
	var i Players
	err := row.Scan(&i.ID, &i.Name, &i.Created)
	return i, err
}

const playerCreate = `-- name: PlayerCreate :one
INSERT INTO players (name) VALUES ($1) RETURNING id
`

func (q *Queries) PlayerCreate(ctx context.Context, name string) (int32, error) {
	row := q.db.QueryRow(ctx, playerCreate, name)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const playerDelete = `-- name: PlayerDelete :exec
DELETE FROM players WHERE id = $1
`

func (q *Queries) PlayerDelete(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, playerDelete, id)
	return err
}
