// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: point_changes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const pointChangeCreate = `-- name: PointChangeCreate :one
INSERT INTO point_changes (game_id, player_id, delta, infraction_id)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type PointChangeCreateParams struct {
	GameID       string      `json:"game_id"`
	PlayerID     pgtype.Int4 `json:"player_id"`
	Delta        int32       `json:"delta"`
	InfractionID pgtype.Int4 `json:"infraction_id"`
}

// Records a points change. infraction_id is set when the change came from an
// affirmed accusation, or NULL for a direct host adjustment.
func (q *Queries) PointChangeCreate(ctx context.Context, arg PointChangeCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, pointChangeCreate,
		arg.GameID,
		arg.PlayerID,
		arg.Delta,
		arg.InfractionID,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
