// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package sqlc

import (
	"context"
)

const gameCreate = `-- name: GameCreate :exec


INSERT INTO games (name, code, owner)
VALUES (?1, ?2, ?3) 
RETURNING code
`

type GameCreateParams struct {
	Name  string `json:"name"`
	Code  string `json:"code"`
	Owner int64  `json:"owner"`
}

// Player
// PlayerDelete
// CardCreate
// Card
// CardEdit
// CardDelete
func (q *Queries) GameCreate(ctx context.Context, arg GameCreateParams) error {
	_, err := q.db.Exec(ctx, gameCreate, arg.Name, arg.Code, arg.Owner)
	return err
}

const playerCreate = `-- name: PlayerCreate :exec
INSERT INTO players (name) VALUES (?1) RETURNING id
`

func (q *Queries) PlayerCreate(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, playerCreate, name)
	return err
}
