// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: spins.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const spinPendingModifier = `-- name: SpinPendingModifier :one
SELECT
    spins.id,
    spins.player_id,
    spins.card_id,
    cards.modifier_effect
FROM spins
JOIN cards ON cards.id = spins.card_id
WHERE spins.game_id = $1
  AND spins.ts > COALESCE(
      (SELECT MAX(ts) FROM event_log
       WHERE game_id = $1 AND event_type = 'turn'),
      '1970-01-01'
  )
ORDER BY spins.ts DESC
LIMIT 1
`

type SpinPendingModifierRow struct {
	ID             int32       `json:"id"`
	PlayerID       pgtype.Int4 `json:"player_id"`
	CardID         pgtype.Int4 `json:"card_id"`
	ModifierEffect pgtype.Text `json:"modifier_effect"`
}

// Returns the most recent spin for a game, with modifier info.
// A non-NULL modifier_effect means the spin landed on a modifier.
// Only returns a spin that occurred after the most recent "turn" event,
// so stale spins from before a continue/advance don't look pending.
func (q *Queries) SpinPendingModifier(ctx context.Context, gameID string) (SpinPendingModifierRow, error) {
	row := q.db.QueryRow(ctx, spinPendingModifier, gameID)
	var i SpinPendingModifierRow
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.CardID,
		&i.ModifierEffect,
	)
	return i, err
}
