// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: spins.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const spinLatestElapsedSeconds = `-- name: SpinLatestElapsedSeconds :one
SELECT FLOOR(EXTRACT(EPOCH FROM (now() - ts)))::int AS seconds
FROM spins
WHERE game_id = $1
ORDER BY ts DESC
LIMIT 1
`

// Whole seconds elapsed on the database clock since the most recent spin in a
// game. Used to time the active prompt challenge (the latest spin is the
// prompt spin while the game sits in the prompt state).
func (q *Queries) SpinLatestElapsedSeconds(ctx context.Context, gameID string) (int32, error) {
	row := q.db.QueryRow(ctx, spinLatestElapsedSeconds, gameID)
	var seconds int32
	err := row.Scan(&seconds)
	return seconds, err
}

const spinPendingModifier = `-- name: SpinPendingModifier :one
SELECT
    spins.id,
    spins.player_id,
    spins.card_id,
    spins.ts,
    cards.type,
    cards.front,
    cards.modifier_effect
FROM spins
JOIN cards ON cards.id = spins.card_id
WHERE spins.game_id = $1
  AND spins.ts >= COALESCE(
      (SELECT MAX(ts) FROM event_log
       WHERE game_id = $1 AND event_type = 'turn'),
      '1970-01-01'
  )
ORDER BY spins.ts DESC
LIMIT 1
`

type SpinPendingModifierRow struct {
	ID             int32            `json:"id"`
	PlayerID       pgtype.Int4      `json:"player_id"`
	CardID         pgtype.Int4      `json:"card_id"`
	Ts             pgtype.Timestamp `json:"ts"`
	Type           string           `json:"type"`
	Front          string           `json:"front"`
	ModifierEffect pgtype.Text      `json:"modifier_effect"`
}

// Returns the most recent spin for a game, with the drawn card's type, face,
// effect, and the spin time. A non-NULL modifier_effect means the spin landed
// on a modifier; type 'prompt' means it landed on a prompt challenge (ts gates
// how soon the host may rule it failed).
// Only returns a spin that occurred after the most recent "turn" event,
// so stale spins from before a continue/advance don't look pending.
func (q *Queries) SpinPendingModifier(ctx context.Context, gameID string) (SpinPendingModifierRow, error) {
	row := q.db.QueryRow(ctx, spinPendingModifier, gameID)
	var i SpinPendingModifierRow
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.CardID,
		&i.Ts,
		&i.Type,
		&i.Front,
		&i.ModifierEffect,
	)
	return i, err
}
