// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: suggestions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const suggestionCreate = `-- name: SuggestionCreate :one
INSERT INTO suggestions (front, back)
VALUES ($1, $2)
RETURNING id
`

type SuggestionCreateParams struct {
	Front string `json:"front"`
	Back  string `json:"back"`
}

func (q *Queries) SuggestionCreate(ctx context.Context, arg SuggestionCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, suggestionCreate, arg.Front, arg.Back)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const suggestionDelete = `-- name: SuggestionDelete :exec
DELETE FROM suggestions
WHERE id = $1
`

func (q *Queries) SuggestionDelete(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, suggestionDelete, id)
	return err
}

const suggestionGet = `-- name: SuggestionGet :one
SELECT id, front, back, status, issue_url, notes, created FROM suggestions
WHERE id = $1
`

func (q *Queries) SuggestionGet(ctx context.Context, id int32) (Suggestions, error) {
	row := q.db.QueryRow(ctx, suggestionGet, id)
	var i Suggestions
	err := row.Scan(
		&i.ID,
		&i.Front,
		&i.Back,
		&i.Status,
		&i.IssueUrl,
		&i.Notes,
		&i.Created,
	)
	return i, err
}

const suggestionSetStatus = `-- name: SuggestionSetStatus :exec
UPDATE suggestions
SET status = $2,
    issue_url = $3,
    notes = $4
WHERE id = $1
`

type SuggestionSetStatusParams struct {
	ID       int32       `json:"id"`
	Status   string      `json:"status"`
	IssueUrl pgtype.Text `json:"issue_url"`
	Notes    pgtype.Text `json:"notes"`
}

func (q *Queries) SuggestionSetStatus(ctx context.Context, arg SuggestionSetStatusParams) error {
	_, err := q.db.Exec(ctx, suggestionSetStatus,
		arg.ID,
		arg.Status,
		arg.IssueUrl,
		arg.Notes,
	)
	return err
}

const suggestionsNew = `-- name: SuggestionsNew :many
SELECT id, front, back, status, issue_url, notes, created FROM suggestions
WHERE status = 'new'
ORDER BY created
`

func (q *Queries) SuggestionsNew(ctx context.Context) ([]Suggestions, error) {
	rows, err := q.db.Query(ctx, suggestionsNew)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Suggestions
	for rows.Next() {
		var i Suggestions
		if err := rows.Scan(
			&i.ID,
			&i.Front,
			&i.Back,
			&i.Status,
			&i.IssueUrl,
			&i.Notes,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
