name: Bug report
description: Report something broken or behaving unexpectedly.
title: "[bug]: "
labels: ["bug"]
body:
  - type: input
    id: game-url
    attributes:
      label: Game URL
      description: The game URL where this happened.
      placeholder: https://rulette.grackle.club/abc123
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Build version (in footer, may autopopulate)

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you see? What did you expect to see?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can someone else trigger this? Video or screenshots welcome, where helpful.
      placeholder: |
        1. create a game
        2. ...
        3. ...

  - type: checkboxes
    id: os
    attributes:
      label: Operating system
      options:
        - label: Windows
        - label: macOS
        - label: Linux
        - label: Android
        - label: iOS
        - label: Other

  - type: checkboxes
    id: browser
    attributes:
      label: Browser
      options:
        - label: Firefox
        - label: Chrome
        - label: Chromium
        - label: Brave
        - label: Safari
        - label: Opera

